Apply upstream (rest-server) API changes
In June 2018, dependency rest-server[1] cleaned up its API a
little[2], breaking the Caddy restic plugin build in the process.

Attempting to build Caddy with the plugin leads to the following
errors:

```
build/src/github.com/restic/caddy/setup.go:24:4: undefined: restserver.Config
build/src/github.com/restic/caddy/setup.go:40:19: undefined: restserver.NewMux
```

This commit applies the upstream API changes to fix the errors.

[1]: https://github.com/restic/rest-server
[2]: https://github.com/restic/rest-server/pull/67